"""empty message

Revision ID: 58b45896d786
Revises: 5b5b93403fc8
Create Date: 2025-11-15 14:19:41.362633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58b45896d786'
down_revision = '5b5b93403fc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lost_found_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', sa.Time(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lost_found_posts', schema=None) as batch_op:
        batch_op.drop_column('time')

    # ### end Alembic commands ###
