"""empty message

Revision ID: 676be1cbc1ee
Revises: 652bccf5ab90
Create Date: 2026-01-16 13:26:28.863372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '676be1cbc1ee'
down_revision = '652bccf5ab90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_column('post_id')

    # ### end Alembic commands ###
