"""empty message

Revision ID: 6e0e020fcfc1
Revises: a97b24c5d2bc
Create Date: 2025-12-01 21:00:15.204430

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6e0e020fcfc1'
down_revision = 'a97b24c5d2bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('messages_ibfk_2'), type_='foreignkey')
        batch_op.drop_column('receiver_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receiver_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('messages_ibfk_2'), 'credentials', ['receiver_id'], ['id'])

    # ### end Alembic commands ###
