"""empty message

Revision ID: a97b24c5d2bc
Revises: 94f74877acea
Create Date: 2025-11-28 00:02:35.455329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a97b24c5d2bc'
down_revision = '94f74877acea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lost_found_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=15), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lost_found_posts', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
